version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: ./.docker/frontend/Dockerfile
    container_name: frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev"
